In [2]:
#9.1) 
#a) escriba en forma matricial el conjunto siguiente de ecuaciones
#50=5x3+2x2,10-x1=x3,3x2+8x1=20
print("    | 0 2  5  50|")
print("[a]=|-1 0 -1 -10|")
print("    | 8 3  0  20|")
#b)escriba la transpuesta de la matriz de coeficientes 
print("b")
a=[0,2,5,50],[-1,0,-1,-10],[8,3,0,20]

a1=[0,0,0],[0,0,0],[0,0,0],[0,0,0]

for x in range(0,3):
    for y in range (0,4):
        a1[y][x]=a[x][y];
        
for x in range(0,4):
        print (a1[x][0],a1[x][1],a1[x][2]);
    
    

    | 0 2  5  50|
[a]=|-1 0 -1 -10|
    | 8 3  0  20|
b
0 -1 8
2 0 3
5 -1 0
50 -10 20


In [ ]:
#9.2)ciertas matrices estan definidas como sigue
#[a]=|4 7||1 2||5 6|   
#[b]= |4 3 7||1 2 7||1 0 4|     
#[c]= |3||6||1|
#[d]=  |9  4  3 -6||2 -1  7  5|
#[e]= |1 5 8||7 2 3||4 0 6|
#[f]=  |3 0 1||1 7 3|
#[g]= |7 6 4|
#a) ¿cuales son las dimenciones de las matrices?
print("a=3*2")
print("b=3*3")
print("c=3*1")
print("d=2*4")
print("e=3*3")
print("f=2*3")
print("g=1*3")
#b)¿identifique las matrices cuadrada, columna y region?
print("matris cuabradas= b,e")
print("matris columna= c")
print("matris renglon= g")
#c)¿cuales son los valores de los elementos a12, b23,d32,e22,f12,g12?
print("a12=7")
print("b23=7")
print("d32=no hay")
print("e22=2")
print("f12=0")
print("g12=6")
#d)ejecute la operaciones siguiente

print("1:e+b")
import numpy as np
b=np.array([(4,3,7),(1,2,7),(1,0,4)])
e=np.array([(1,5,8),(7,2,3),(4,0,6)])
print ("b= \n", b)
print ("e= \n", e)
print ("b*e =")
print (b*e)

print("2:a+f")
from numpy import matrix 
a=matrix([[4,7],[1,2],[5,6]])
f=matrix([[3,0,1],[1,7,3]])
print ("a= \n", a)
print ("f= \n", f)
print ("a+f =")
print (a+f)

print("3:b-3")
from numpy import matrix 
b=matrix([[4,3,7],[1,2,7],[1,0,4]])
e=matrix([[1,5,8],[7,2,3],[4,0,6]])
print ("b= \n", b)
print ("e= \n", e)
print ("b-e =")
print (b-e)

print("4;7*b")
from numpy import matrix 
b=matrix([[4,3,7],[1,2,7],[1,0,4]])
print ("b= \n", b)
print ("7*b =")
print (7*b)

print("5:e*b")
from numpy import matrix 
b=matrix([[4,3,7],[1,2,7],[1,0,4]])
e=matrix([[1,5,8],[7,2,3],[4,0,6]])
print ("b= \n", b)
print ("e= \n", e)
print ("e*b =")
print (e*b)

print("6:c^t")
from numpy import matrix 
M1=[[3],[6],[1]]
M2=[[0,0,0]]
for i in range(3):
    for j in range(1):
        M2[j][i] = M1[i][j]
for i in range(1):
    print(M2[i])
    
print("7:b*a")
from numpy import matrix 
b=matrix([[4,3,7],[1,2,7],[1,0,4]])
a=matrix([[4,7],[1,2],[5,6]])
print ("b= \n", b)
print ("a= \n", a)
print ("b *a=")
print (b*a)

print("8:d^t")
from numpy import matrix 
M1=[[9,4,3,-6],[2,-1,7,5]]
M2=[[0,0],[0,0],[0,0],[0,0]]
for i in range(2):
    for j in range(4):
        M2[j][i] = M1[i][j]
for i in range(4):
    print(M2[i])

print("9:a*c")  
from numpy import matrix 
c=matrix([[3],[6],[1]])
a=matrix([[4,7],[1,2],[5,6]])
print ("c= \n", c)
print ("a= \n", a)
print ("a*c=")
print (a*c)

print("10:i*b")
from numpy import matrix 
M1=matrix([[4,3,7],[1,2,7],[1,0,4]])
M2=matrix([[0,0,0],[0,0,0],[0,0,0]])
for i in range(3):
     M1[(i),(i)]=1
print (M1)

print("11:e^t*e")
from numpy import matrix 
M1=matrix([[1,5,8],[7,2,3],[4,0,6]])
M2=matrix([[0,0,0],[0,0,0],[0,0,0]])
for i in range(3):
    for j in range(3):
        M2[(j),(i)] = M1[(i),(j)]
print (M2*M1)

print("12:c^t*c")
from numpy import matrix 
M1=matrix([[3],[6],[1]])
M2=matrix([[0,0,0]])
for i in range(3):
    for j in range(1):
        M2[(j),(i)] = M1[(i),(j)]
print (M2*M1)  

In [ ]:
 9.3)Se definen tres matrices como sigue
      |1  6|
    a=|3 10|
      |7  4|
            
      | 1  3|
    b=|0.5 2|
      
      | 2  -2|
    c=|-3   1|
      
 a) Ejecute todas las multiplicaciones que sea posible calcular entre parejas de las matrices.
b) Utilice el método del recuadro PT3.2 para justificar por qué no se puede multiplicar a las demás parejas. 
c) Emplee los resultado del inciso a) para ilustrar por qué es importante el orden de la multiplicación.

In [57]:
#a) Ejecute todas las multiplicaciones que sea posible calcular entre parejas de las matrices.
a=matrix([[1,6],[3,10],[7,4]])
b=matrix([[1,3],[0.5,2]])
c=matrix([[2,-2],[-3,1]])
print ("a= \n", a)
print ("b= \n", b)
print ("c= \n", c)
print ("a*b=")
print (a * b)
print ("a*c=")
print (a * c)
print ("b*c=")
print (b * c)

#b) Utilice el método del recuadro PT3.2 para justificar por qué no se puede multiplicar a las demás parejas.

#podemos ver que el metodo pt3.2 de la pagina 263 muestra que para multiplicar dos matrices se toma la columnapor la fila 
#Observe cómo este método simple explica el porqué es imposible multiplicar dos matrices si el número de columnas de la 
#primera matriz no es igual al número de renglones en la segunda matriz. 
#Note también la importancia del orden en la multiplicación (es decir, la multiplicación de matrices no es conmutativa
 
#c) Emplee los resultado del inciso a) para ilustrar por qué es importante el orden de la multiplicación.

a=matrix([[1,6],[3,10],[7,4]])
b=matrix([[1,3],[0.5,2]])
c=matrix([[2,-2],[-3,1]])


print ("a= \n", a)
print ("b= \n", b)
print ("c= \n", c)


print ("b*a=")
print (b*a)
print ("c*a=")
print (c*a)
print ("c*b=")
print (c*b)
# se guenera error


a= 
 [[ 1  6]
 [ 3 10]
 [ 7  4]]
b= 
 [[ 1.   3. ]
 [ 0.5  2. ]]
c= 
 [[ 2 -2]
 [-3  1]]
a*b=
[[  4.  15.]
 [  8.  29.]
 [  9.  29.]]
a*c=
[[-16   4]
 [-24   4]
 [  2 -10]]
b*c=
[[-7.  1.]
 [-5.  1.]]


In [ ]:
9.4 Use el método gráfico para resolver el sistema siguiente
4x1 – 8x2 = –24 
x1 + 6x2 = 34
Compruebe el resultado por medio de sustituirlo en las ecuaciones.

In [3]:
#x2=(-24-4x1)/-8
#x2=(34-x1)/6

from numpy import *
import matplotlib.pyplot as plt
x2=0;
y2=0;
x=[]
z=[]
y=[]
p=[]
print("x2=(-24-4x1)/-8");
for i in range (6):
    x2=(-24-4*i)/-8
    x.append(i)
    y.append(x2)
    #print(i,x2);
#print("x2=(34-x1)/6");
print(0, 0.0)
for i in range(6):
    x2=(34-i)/6
    z.append(i)
    p.append(x2)
    #print(i,x2);
plt.plot(x,y,'r',linewidth=2,label='x2=(-24-4x1)/-8')
plt.hold(True)
plt.plot(z,p,'k--',linewidth=2,label='x2=(34-x1)/6')
plt.legend(loc = 2)
plt.show()

x1=4
x2=5
print("se comprueva los valore de x1= ",x1,"x2= ",x2)
print("4x1 – 8x2 =",4*x1-8*x2);
print("x1 + 6x2 =",x1+6*x2);

x2=(-24-4x1)/-8
0 0.0
se comprueva los valore de x1=  4 x2=  5
4x1 – 8x2 = -24
x1 + 6x2 = 34


In [7]:
9.5 Dado el sistema de ecuaciones siguiente
–1.1x1 + 10x2 = 120
–2x1 + 17.4x2 = 174
 a)  Resuélvalo gráficamente y compruebe el resultado con la sustitución en las ecuaciones. 
b) Sobre la base de la solución gráfica, ¿qué se espera con respecto de la condición del sistema? 
c)  Calcule el determinante. 
d)  Resuelva por medio de la eliminación de incógnitas.

SyntaxError: invalid syntax (<ipython-input-7-68975c08db6f>, line 1)

In [22]:
# a)  Resuélvalo gráficamente y compruebe el resultado con la sustitución en las ecuaciones. 

print("a")
#–1.1x1 + 10x2 = 120
#–2x1 + 17.4x2 = 174
from numpy import *
import matplotlib.pyplot as plt
x2=0;
y2=0;
x=[]
z=[]
y=[]
p=[]
i=300
print("x2=(120+1.1*x1)/10");
for i in range (500):
    x2=(120+1.1*i)/10
    x.append(i)
    y.append(x2)
    #print(i,x2);
#print("x2=(34-x1)/6");
print(0, 0.0)
i=300
for i in range(500):
    x2=(174+2*i)/17.4
    z.append(i)
    p.append(x2)
    #print(i,x2);
plt.plot(x,y,'r',linewidth=2,label='x2=(120+1.1*x1)/10')
plt.hold(True)
plt.plot(z,p,'k--',linewidth=2,label='x2=(174+2*i)/17.4')
plt.legend(loc = 2)
plt.show()
x1=404.6
x2=56.5
print("se comprueva los valore de x1= ",x1,"x2= ",x2)
print("–1.1x1 + 10x2 =",-1.1*x1+10*x2);
print("–2x1 + 17.4x2 =",-2*x1+17.4*x2);

print("b")
#b) Sobre la base de la solución gráfica, ¿qué se espera con respecto de la condición del sistema? 
#se espera que la dos rectas respectivas e cada ecuacion no se vuelvan a interceptar
print("c")
#c)  Calcule el determinante. 
#–1.1x1 + 10x2 = 120
#–2x1 + 17.4x2 = 174
import numpy
M = [[-1.1,10], [-2,17.4]]
print (numpy.linalg.det(M))
print("d")
#d)  Resuelva por medio de la eliminación de incógnitas.
import numpy
m=int(input("Valor de m:"))
n=int(input("Valor de n:"))
matrix = numpy.zeros((m,n))
vector= numpy.zeros((n))
x=numpy.zeros((m))
print( 'Introduce la matriz de coeficientes y el vector solución')
for r in range(0,m):
    for c in range(0,n):
        
        matrix[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"]  "))
        
    vector[(r)]=(input("b["+str(r+1)+"]"))
             
print (matrix)
                 
for k in range(0,m):
    for r in range(k+1,m):
        factor=(matrix[r,k]/matrix[k,k])
        vector[r]=vector[r]-(factor*vector[k])
        for c in range(0,n):
            matrix[r,c]=matrix[r,c]-(factor*matrix[k,c])


#sustitución hacia atrás
x[m-1]=vector[m-1]/matrix[m-1,m-1]
print (x[m-1])
for r in range(m-2,-1,-1):
    suma=0
    for c in range(0,n):
        suma=suma+matrix[r,c]*x[c]
    x[r]=(vector[r]-suma)/matrix[r,r]
print ('Resultado matriz')
print(matrix)
print ('Resultado del vector')
print(vector)
print ('Resultados de la forma x1+x2+x3: ')
print(x)
#–1.1x1 + 10x2 = 120
#–2x1 + 17.4x2 = 174

x2=(120+1.1*x1)/10
0 0.0
se comprueva los valore de x1=  404.6 x2=  56.5
–1.1x1 + 10x2 = 119.93999999999994
–2x1 + 17.4x2 = 173.89999999999986


In [ ]:
9.6 Para el sistema de ecuaciones que sigue
2x2 + 5x3 = 9 
2x1 + x2 + x3 = 9 
3x1 + x2 = 10
 a)  Calcule el determinante. 
b)  Use la regla de Cramer para encontrar cuál es el valor de las x. 
c)  Sustituya el resultado en las ecuaciones originales para efectos de comprobación.

In [8]:
#a)  Calcule el determinante.
#2x2 + 5x3 = 9 
#2x1 + x2 + x3 = 9 
#3x1 + x2 = 10
#a=[0,2,5,9],[2,1,1,9],[3,1,0,10]
a=[0,2,5],[2,1,1],[3,1,0]
a1=((a[1][1]*a[2][2])-(a[1][2]*a[2][1]))*a[0][0]
a2=(a[1][0]*a[2][2]-a[1][2]*a[2][0])*a[0][1]
a3=(a[1][0]*a[2][1]-a[1][1]*a[2][0])*a[0][2]
determinante=a1-a2+a3
print ("a= \n", b)
print ("determinante=",determinante)



a= 
 [[0 2 5]
 [2 1 1]
 [3 1 0]]
b*a= 1


In [11]:
#b)  Use la regla de Cramer para encontrar cuál es el valor de las x. 

#a=[0,2,5,9],[2,1,1,9],[3,1,0,10]

#a=[0,2,5],[2,1,1],[3,1,0]

a11,a12,a13,b1=0,2,5,9
a21,a22,a23,b2=2,1,1,9
a31,a32,a33,b3=3,1,0,10
X=[]


A1,A2,A3=round(a22*a33-a32*a23,2),round(a21*a33-a31*a23,2),round(a21*a32-a31*a22,2)
X11,X12,X13=round(a22*a33-a32*a23,4),round(b2*a33-b3*a23,4),round(b2*a32-b3*a22,4)
X21,X22,X23=round(b2*a33-b3*a23,4),round(a21*a33-a31*a23,4),round(a21*b3-a31*b2,4)
X31,X32,X33=round(a22*b3-a32*b2,4),round(a21*b3-a31*b2,4),round(a21*a32-a31*a22,4)
Determinante=round(a11*A1-a12*A2+a13*A3,4)
DeterminanteX1=round(b1*X11-a12*X12+a13*X13,6)
DeterminanteX2=round(a11*X21-b1*X22+a13*X23,6)
DeterminanteX3=round(a11*X31-a12*X32+b1*X33,6)

print ("{0:15}|{1:5}  {2:5}  {3:5} : {4:5} |".format("",a11,a12,a13,b1));
print ("{0:15}|{1:5}  {2:5}  {3:5} : {4:5} |".format("Matriz A =",a21,a22,a23,b2));
print ("{0:15}|{1:5}  {2:5}  {3:5} : {4:5} |".format("",a31,a32,a33,b3));

print ("\n{0:15}|{1:5}  {2:5}  {3:5} |".format("",a11,a12,a13));
print ("{0:15}|{1:5}  {2:5}  {3:5} |".format("Determinante =",a21,a22,a23));
print ("{0:15}|{1:5}  {2:5}  {3:5} |".format("",a31,a32,a33));

print ("\nMenores");

print ("\n{0:5}|{1:5}  {2:5} | ==> ({3:1})*({4:3})-({5:1})*({6:1})= {7:1}".format("A1 =",a22,a23,a22,a33,a32,a23,A1));
print ("{0:5}|{1:5}  {2:5} |".format("",a32,a33));

print ("\n{0:5}|{1:5}  {2:5} | ==> ({3:1})*({4:3})-({5:1})*({6:1})= {7:1}".format("A1 =",a21,a23,a21,a33,a31,a23,A2));
print ("{0:5}|{1:5}  {2:5} |".format("",a31,a33));

print ("\n{0:5}|{1:5}  {2:5} | ==> ({3:1})*({4:3})-({5:1})*({6:1})= {7:1}".format("A1 =",a21,a22,a21,a32,a31,a22,A3));
print ("{0:5}|{1:5}  {2:5} |".format("",a31,a32));

print ("\n{0:5} ({1:1})*({2:1})-({3:1})*({4:1})+({5:1})*({6:1})= {7:1}".format("Determinante =",a11,A1,a12,A2,a13,A3,Determinante));

print ("\n{0:5}|{1:5}  {2:5}  {3:5} |".format("",b1,a12,a13));
print ("{0:5}|{1:5}  {2:5}  {3:5} |".format("",b2,a22,a23));
print ("{0:5}|{1:5}  {2:5}  {3:5} |      {4:5}".format("",b3,a32,a33,DeterminanteX1));
print ("{0:5}|{1:5}| ==> {2:5} = {3:5}".format("X1 =","--------------------","-------",round(DeterminanteX1/Determinante,2)));
print ("{0:5} {1:5} {2:5}             {3:5}".format("","",Determinante,Determinante));

print ("\n{0:5}|{1:5}  {2:5}  {3:5} |".format("",a11,b1,a13));
print ("{0:5}|{1:5}  {2:5}  {3:5} |".format("",a21,b2,a23));
print ("{0:5}|{1:5}  {2:5}  {3:5} |      {4:5}".format("",a31,b3,a33,DeterminanteX2));
print ("{0:5}|{1:5}| ==> {2:5} = {3:5}".format("X2 =","--------------------","-------",round(DeterminanteX2/Determinante,2)));
print ("{0:5} {1:5} {2:5}             {3:5}".format("","",Determinante,Determinante));

print ("\n{0:5}|{1:5}  {2:5}  {3:5} |".format("",a11,a12,b1));
print ("{0:5}|{1:5}  {2:5}  {3:5} |".format("",a21,a22,b2));
print ("{0:5}|{1:5}  {2:5}  {3:5} |     {4:5}".format("",a31,a32,b3,DeterminanteX3));
print ("{0:5}|{1:5}| ==> {2:5} = {3:5}".format("X3 =","--------------------","-------",round(DeterminanteX3/Determinante,2)));
print ("{0:5} {1:5} {2:5}             {3:5}".format("","",Determinante,Determinante));


               |    0      2      5 :     9 |
Matriz A =     |    2      1      1 :     9 |
               |    3      1      0 :    10 |

               |    0      2      5 |
Determinante = |    2      1      1 |
               |    3      1      0 |

Menores

A1 = |    1      1 | ==> (1)*(  0)-(1)*(1)= -1
     |    1      0 |

A1 = |    2      1 | ==> (2)*(  0)-(3)*(1)= -3
     |    3      0 |

A1 = |    2      1 | ==> (2)*(  1)-(3)*(1)= -1
     |    3      1 |

Determinante = (0)*(-1)-(2)*(-3)+(5)*(-1)= 1

     |    9      2      5 |
     |    9      1      1 |
     |   10      1      0 |          6
X1 = |--------------------| ==> ------- =   6.0
                1                 1

     |    0      9      5 |
     |    2      9      1 |
     |    3     10      0 |         -8
X2 = |--------------------| ==> ------- =  -8.0
                1                 1

     |    0      2      9 |
     |    2      1      9 |
     |    3      1     10 |         5
X3 = |--------------------| ==

In [12]:
#c)  Sustituya el resultado en las ecuaciones originales para efectos de comprobación.
#2x2 + 5x3 = 9 
#2x1 + x2 + x3 = 9 
#3x1 + x2 = 10
x1=6
x2=-8
x3=5


print("2x2 + 5x3 =",2*x2+5*x3)
print("2x1 + x2 + x3 =",2*x1+x2+x3)
print("3x1 + x2 =",3*x1+x2)



2x2 + 5x3 = 9
2x1 + x2 + x3 = 9
3x1 + x2 = 10


In [ ]:
9.7 Dadas las ecuaciones
0.5x1 – x2 = –9.5 
1.02x1 – 2x2 = –18.8
a)  Resuelva en forma gráfica. 
b)  Calcule el determinante. 
c)  Con base en los incisos a) y b), ¿qué es de esperarse con respecto de la condición del sistema? 
d)  Resuelva por medio de la eliminación de incógnitas. 
e)  Resuelva otra vez, pero modifique ligeramente el elemento a11 a 0.52. Interprete sus resultados.

In [18]:
#a)  Resuelva en forma gráfica. 

#0.5x1 – x2 = –9.5 
#x2=-(-9.5+0.5*x1)
#1.02x1 – 2x2 = –18.8
#x2=-(-18.8-1.02*x1)/2

from numpy import *
import matplotlib.pyplot as plt
x2=0;
y2=0;
x=[]
z=[]
y=[]
p=[]
print("x2=-(-9.5+0.5*x1)");
for i in range (2):
    x2=-(-9.5+0.5*i)
    x.append(i)
    y.append(x2)
    #print(i,x2);
print("x2=-(-18.8-1.02*x1)/2");
#print(0, 0.0)
for i in range(2):
    x2=-(-18.8-1.02*i)/2
    z.append(i)
    p.append(x2)
    #print(i,x2);
plt.plot(x,y,'r',linewidth=2,label='x2=(-24-4x1)/-8')
plt.hold(True)
plt.plot(z,p,'k--',linewidth=2,label='x2=(34-x1)/6')
plt.legend(loc = 2)
plt.show()

x1=0.0988
x2=9.45
print("se comprueva los valore de x1= ",x1,"x2= ",x2)
print("0.5x1 – x2 =  ",0.5*x1-x2);
print("1.02x1 – 2x2 =",1.02*x1-2*x2);


x2=-(-9.5+0.5*x1)
x2=-(-18.8-1.02*x1)/2
se comprueva los valore de x1=  0.0988 x2=  9.45
0.5x1 – x2 =   -9.400599999999999
1.02x1 – 2x2 = -18.799224


In [20]:
#b)  Calcule el determinante.

#0.5x1 – x2 = –9.5 
#1.02x1 – 2x2 = –18.8


#a=[0.5,-1,-9.5],[1.02,-2,-18.8]

a=[0.5,-1],[1.02,-2]

a1=((a[0][0]*a[1][1])-(a[0][1]*a[1][0]))



determinante=a1

print ("a= \n", b)
print ("determinante=",determinante)



a= 
 [[0 2 5]
 [2 1 1]
 [3 1 0]]
determinante= 0.020000000000000018


In [ ]:
#c)  Con base en los incisos a) y b), ¿qué es de esperarse con respecto de la condición del sistema? 
se espera que x2 tienda mas rapido al infinito que x1


In [4]:
#d)  Resuelva por medio de la eliminación de incógnitas. 

import numpy
m=int(input("Valor de m:"))
n=int(input("Valor de n:"))
matrix = numpy.zeros((m,n))
vector= numpy.zeros((n))
x=numpy.zeros((m))
print( 'Introduce la matriz de coeficientes y el vector solución')
for r in range(0,m):
    for c in range(0,n):
        
        matrix[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"]  "))
        
    vector[(r)]=(input("b["+str(r+1)+"]"))
             
print (matrix)
                 
for k in range(0,m):
    for r in range(k+1,m):
        factor=(matrix[r,k]/matrix[k,k])
        vector[r]=vector[r]-(factor*vector[k])
        for c in range(0,n):
            matrix[r,c]=matrix[r,c]-(factor*matrix[k,c])


#sustitución hacia atrás
x[m-1]=vector[m-1]/matrix[m-1,m-1]
print (x[m-1])
for r in range(m-2,-1,-1):
    suma=0
    for c in range(0,n):
        suma=suma+matrix[r,c]*x[c]
    x[r]=(vector[r]-suma)/matrix[r,r]
print ('Resultado matriz')
print(matrix)
print ('Resultado del vector')
print(vector)
print ('Resultados de la forma x1+x2+x3: ')
print(x)

#0.5x1 – x2 = –9.5 
#1.02x1 – 2x2 = –18.8

Valor de m:2
Valor de n:2
Introduce la matriz de coeficientes y el vector solución
Elemento a[1,1]  0.5
Elemento a[1,2]  -1
b[1]-9.5
Elemento a[2,1]  1.02
Elemento a[2,2]  -2
b[2]-18.8
[[ 0.5  -1.  ]
 [ 1.02 -2.  ]]
14.5
Resultado matriz
[[ 0.5  -1.  ]
 [ 0.    0.04]]
Resultado del vector
[-9.5   0.58]
Resultados de la forma x1+x2+x3: 
[ 10.   14.5]


In [3]:
#e)  Resuelva otra vez, pero modifique ligeramente el elemento a11 a 0.52. Interprete sus resultados.
import numpy
m=int(input("Valor de m:"))
n=int(input("Valor de n:"))
matrix = numpy.zeros((m,n))
vector= numpy.zeros((n))
x=numpy.zeros((m))
print( 'Introduce la matriz de coeficientes y el vector solución')
for r in range(0,m):
    for c in range(0,n):
        
        matrix[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"]  "))
        
    vector[(r)]=(input("b["+str(r+1)+"]"))
             
print (matrix)
                 
for k in range(0,m):
    for r in range(k+1,m):
        factor=(matrix[r,k]/matrix[k,k])
        vector[r]=vector[r]-(factor*vector[k])
        for c in range(0,n):
            matrix[r,c]=matrix[r,c]-(factor*matrix[k,c])


#sustitución hacia atrás
x[m-1]=vector[m-1]/matrix[m-1,m-1]
print (x[m-1])
for r in range(m-2,-1,-1):
    suma=0
    for c in range(0,n):
        suma=suma+matrix[r,c]*x[c]
    x[r]=(vector[r]-suma)/matrix[r,r]
print ('Resultado matriz')
print(matrix)
print ('Resultado del vector')
print(vector)
print ('Resultados de la forma x1+x2+x3: ')
print(x)

#0.52x1 – x2 = –9.5 
#1.02x1 – 2x2 = –18.8

Valor de m:2
Valor de n:2
Introduce la matriz de coeficientes y el vector solución
Elemento a[1,1]  0.52
Elemento a[1,2]  -1
b[1]-9.5
Elemento a[2,1]  1.02
Elemento a[2,2]  -2
b[2]-18.8
[[ 0.52 -1.  ]
 [ 1.02 -2.  ]]
4.3
Resultado matriz
[[ 0.52       -1.        ]
 [ 0.         -0.03846154]]
Resultado del vector
[-9.5        -0.16538462]
Resultados de la forma x1+x2+x3: 
[-10.   4.3]


9.8 Dadas las ecuaciones siguientes
10x1 + 2x2 – x3 = 27 
–3x1 – 6x2 + 2x3 = –61.5 
x1 + x2 + 5x3 = –21.5
 a)  Resuelva por eliminación de Gauss simple. Efectúe todos los pasos del cálculo. 
b)  Sustituya los resultados en las ecuaciones originales a fin de comprobar sus respuestas.

In [5]:

# a)  Resuelva por eliminación de Gauss simple. Efectúe todos los pasos del cálculo. 
import numpy
m=int(input("Valor de m:"))
n=int(input("Valor de n:"))
matrix = numpy.zeros((m,n))
vector= numpy.zeros((n))
x=numpy.zeros((m))
print( 'Introduce la matriz de coeficientes y el vector solución')
for r in range(0,m):
    for c in range(0,n):
        
        matrix[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"]  "))
        
    vector[(r)]=(input("b["+str(r+1)+"]"))
             
print (matrix)
                 
for k in range(0,m):
    for r in range(k+1,m):
        factor=(matrix[r,k]/matrix[k,k])
        vector[r]=vector[r]-(factor*vector[k])
        for c in range(0,n):
            matrix[r,c]=matrix[r,c]-(factor*matrix[k,c])


#sustitución hacia atrás
x[m-1]=vector[m-1]/matrix[m-1,m-1]
print (x[m-1])
for r in range(m-2,-1,-1):
    suma=0
    for c in range(0,n):
        suma=suma+matrix[r,c]*x[c]
    x[r]=(vector[r]-suma)/matrix[r,r]
print ('Resultado matriz')
print(matrix)
print ('Resultado del vector')
print(vector)
print ('Resultados de la forma x1+x2+x3: ')
print(x)
#10x1 + 2x2 – x3 = 27 
#–3x1 – 6x2 + 2x3 = –61.5 
#x1 + x2 + 5x3 = –21.5

Valor de m:3
Valor de n:3
Introduce la matriz de coeficientes y el vector solución
Elemento a[1,1]  10
Elemento a[1,2]  2
Elemento a[1,3]  -1
b[1]27
Elemento a[2,1]  -3
Elemento a[2,2]  -6
Elemento a[2,3]  2
b[2]-61.5
Elemento a[3,1]  1
Elemento a[3,2]  1
Elemento a[3,3]  5
b[3]-21.5
[[ 10.   2.  -1.]
 [ -3.  -6.   2.]
 [  1.   1.   5.]]
-6.0
Resultado matriz
[[ 10.           2.          -1.        ]
 [  0.          -5.4          1.7       ]
 [  0.           0.           5.35185185]]
Resultado del vector
[ 27.         -53.4        -32.11111111]
Resultados de la forma x1+x2+x3: 
[ 0.5  8.  -6. ]


In [6]:
#10x1 + 2x2 – x3 = 27 
#–3x1 – 6x2 + 2x3 = –61.5 
#x1 + x2 + 5x3 = –21.5 
#b)  Sustituya los resultados en las ecuaciones originales a fin de comprobar sus respuestas.
x1=0.5
x2=8
x3=-6
print("10x1 + 2x2 – x3 =",10*x1 + 2*x2 - x3)
print("–3x1 – 6x2 + 2x3 =",-3*x1 - 6*x2 + 2*x3 )
print("x1 + x2 + 5x3 =",x1 + x2 + 5*x3 )

10x1 + 2x2 – x3 = 27.0
–3x1 – 6x2 + 2x3 = -61.5
x1 + x2 + 5x3 = -21.5
